# Generated by Django 5.2.8 on 2025-11-12 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de Lançamento')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actor', verbose_name='Atores/Atrizes')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='genres.genre', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ('-release_year', 'title'),
            },
        ),
    ]
