# Generated by Django 5.2.8 on 2025-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nationality', models.CharField(max_length=64, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Ator/Atriz',
                'verbose_name_plural': 'Atores/Atrizes',
                'ordering': ('name',),
            },
        ),
    ]
